// The list of all commands.
// Each command definition CUSTOM_COMMAND_SIG(name) or CUSTOM_UI_COMMAND_SIG(name) needs one line here.
// scripts/check-commands.sh checks this.
// This file has no include guard. Include it more than once.
COMMAND(allow_mouse, false, "Shows the mouse and causes all mouse input to be processed normally.")
COMMAND(auto_indent_line_at_cursor, false, "Auto-indents the line on which the cursor sits.")
COMMAND(auto_indent_range, false, "Auto-indents the range between the cursor and the mark.")
COMMAND(auto_indent_whole_file, false, "Audo-indents the entire current buffer.")
COMMAND(backspace_alpha_numeric_boundary, false, "Delete characters between the cursor position and the first alphanumeric boundary to the left.")
COMMAND(backspace_char, false, "Deletes the character to the left of the cursor.")
COMMAND(basic_change_active_panel, false, "Change the currently active panel, moving to the panel with the next highest view_id.  Will not skipe the build panel if it is open.")
COMMAND(begin_clipboard_collection_mode, true, "Allows the user to copy multiple strings from other applications before switching to 5ed and pasting them all.")
COMMAND(build_in_build_panel, false, "Looks for a build.sh or makefile in the current and parent directories.  Runs the first that it finds and prints the output to *compilation*.  Puts the *compilation* buffer in a panel at the footer of the current view.")
COMMAND(build_search, false, "Looks for a build.sh or makefile in the current and parent directories.  Runs the first that it finds and prints the output to *compilation*.")
COMMAND(center_view, false, "Centers the view vertically on the line on which the cursor sits.")
COMMAND(change_active_panel, false, "Change the currently active panel, moving to the panel with the next highest view_id.")
COMMAND(change_active_panel_backwards, false, "Change the currently active panel, moving to the panel with the next lowest view_id.")
COMMAND(change_to_build_panel, false, "If the special build panel is open, makes the build panel the active panel.")
COMMAND(clean_all_lines, false, "Removes trailing whitespace from all lines and removes all blank lines in the current buffer.")
COMMAND(clean_trailing_whitespace, false, "Removes trailing whitespace from all lines in the current buffer.")
COMMAND(clear_all_themes, false, "Clear the theme list")
COMMAND(clear_clipboard, false, "Clears the history of the clipboard")
COMMAND(click_set_cursor, false, "Sets the cursor position to the mouse position.")
COMMAND(click_set_cursor_and_mark, false, "Sets the cursor position and mark to the mouse position.")
COMMAND(click_set_cursor_if_lbutton, false, "If the mouse left button is pressed, sets the cursor position to the mouse position.")
COMMAND(click_set_mark, false, "Sets the mark position to the mouse position.")
COMMAND(clipboard_record_clip, false, "In response to a new clipboard contents events, saves the new clip onto the clipboard history")
COMMAND(close_all_code, false, "Closes any buffer with a filename ending with an extension configured to be recognized as a code file type.")
COMMAND(close_build_panel, false, "If the special build panel is open, closes it.")
COMMAND(close_panel, false, "Closes the currently active panel if it is not the only panel open.")
COMMAND(command_lister, true, "Opens an interactive list of all registered commands.")
COMMAND(comment_line, false, "Insert '//' at the beginning of the line after leading whitespace.")
COMMAND(comment_line_toggle, false, "Turns uncommented lines into commented lines and vice versa for comments starting with '//'.")
COMMAND(copy, false, "Copy the text in the range from the cursor to the mark onto the clipboard.")
COMMAND(cursor_mark_swap, false, "Swaps the position of the cursor and the mark.")
COMMAND(cut, false, "Cut the text in the range from the cursor to the mark onto the clipboard.")
COMMAND(decrease_face_size, false, "Decrease the size of the face used by the current buffer.")
COMMAND(default_file_externally_modified, false, "Notes the external modification of attached files by printing a message.")
COMMAND(default_startup, false, "Default command for responding to a startup event")
COMMAND(default_try_exit, false, "Default command for responding to a try-exit event")
COMMAND(default_view_input_handler, false, "Input consumption loop for default view behavior")
COMMAND(delete_alpha_numeric_boundary, false, "Delete characters between the cursor position and the first alphanumeric boundary to the right.")
COMMAND(delete_char, false, "Deletes the character to the right of the cursor.")
COMMAND(delete_current_scope, false, "Deletes the braces surrounding the currently selected scope.  Leaves the contents within the scope.")
COMMAND(delete_file_query, false, "Deletes the file of the current buffer if 5ed has the appropriate access rights. Will ask the user for confirmation first.")
COMMAND(delete_line, false, "Delete the line the on which the cursor sits.")
COMMAND(delete_range, false, "Deletes the text in the range between the cursor and the mark.")
COMMAND(display_key_codes, false, "Example of input handling loop")
COMMAND(display_text_input, false, "Example of to_writable and leave_current_input_unhandled")
COMMAND(double_backspace, false, "Example of history group helpers")
COMMAND(duplicate_line, false, "Create a copy of the line on which the cursor sits.")
COMMAND(execute_any_cli, false, "Queries for an output buffer name and system command, runs the system command as a CLI and prints the output to the specified buffer.")
COMMAND(execute_previous_cli, false, "If the command execute_any_cli has already been used, this will execute a CLI reusing the most recent buffer name and command.")
COMMAND(exit_5ed, false, "Attempts to close 5ed.")
COMMAND(go_to_user_directory, false, "Go to the 5ed config directory")
COMMAND(goto_beginning_of_file, false, "Sets the cursor to the beginning of the file.")
COMMAND(goto_end_of_file, false, "Sets the cursor to the end of the file.")
COMMAND(goto_first_jump, false, "If a buffer containing jump locations has been locked in, goes to the first jump in the buffer.")
COMMAND(goto_first_jump_same_panel_sticky, false, "If a buffer containing jump locations has been locked in, goes to the first jump in the buffer and views the buffer in the panel where the jump list was.")
COMMAND(goto_jump_at_cursor, false, "If the cursor is found to be on a jump location, parses the jump location and brings up the file and position in another view and changes the active panel to the view containing the jump.")
COMMAND(goto_jump_at_cursor_same_panel, false, "If the cursor is found to be on a jump location, parses the jump location and brings up the file and position in this view, losing the compilation output or jump list.")
COMMAND(goto_line, false, "Queries the user for a number, and jumps the cursor to the corresponding line.")
COMMAND(goto_next_jump, false, "If a buffer containing jump locations has been locked in, goes to the next jump in the buffer, skipping sub jump locations.")
COMMAND(goto_next_jump_no_skips, false, "If a buffer containing jump locations has been locked in, goes to the next jump in the buffer, and does not skip sub jump locations.")
COMMAND(goto_prev_jump, false, "If a buffer containing jump locations has been locked in, goes to the previous jump in the buffer, skipping sub jump locations.")
COMMAND(goto_prev_jump_no_skips, false, "If a buffer containing jump locations has been locked in, goes to the previous jump in the buffer, and does not skip sub jump locations.")
COMMAND(hide_filebar, false, "Sets the current view to hide it's filebar.")
COMMAND(hide_scrollbar, false, "Sets the current view to hide it's scrollbar.")
COMMAND(hit_sfx, false, "Play the hit sound effect")
COMMAND(hms_demo_tutorial, false, "Tutorial for built in 5ed bindings and features.")
COMMAND(if0_off, false, "Surround the range between the cursor and mark with an '#if 0' and an '#endif'")
COMMAND(if_read_only_goto_position, false, "If the buffer in the active view is writable, inserts a character, otherwise performs goto_jump_at_cursor.")
COMMAND(if_read_only_goto_position_same_panel, false, "If the buffer in the active view is writable, inserts a character, otherwise performs goto_jump_at_cursor_same_panel.")
COMMAND(increase_face_size, false, "Increase the size of the face used by the current buffer.")
COMMAND(interactive_kill_buffer, true, "Interactively kill an open buffer.")
COMMAND(interactive_new, true, "Interactively creates a new file.")
COMMAND(interactive_open, true, "Interactively opens a file.")
COMMAND(interactive_open_or_new, true, "Interactively open a file out of the file system.")
COMMAND(interactive_switch_buffer, true, "Interactively switch to an open buffer.")
COMMAND(jump_to_definition, true, "List all definitions in the code index and jump to one chosen by the user.")
COMMAND(jump_to_definition_at_cursor, true, "Jump to the first definition in the code index matching an identifier at the cursor")
COMMAND(jump_to_last_point, false, "Read from the top of the point stack and jump there; if already there pop the top and go to the next option")
COMMAND(keyboard_macro_finish_recording, false, "Stop macro recording, do nothing if macro recording is not already started")
COMMAND(keyboard_macro_replay, false, "Replay the most recently recorded keyboard macro")
COMMAND(keyboard_macro_start_recording, false, "Start macro recording, do nothing if macro recording is already started")
COMMAND(kill_buffer, false, "Kills the current buffer.")
COMMAND(kill_tutorial, false, "If there is an active tutorial, kill it.")
COMMAND(left_adjust_view, false, "Sets the left size of the view near the x position of the cursor.")
COMMAND(list_all_functions_all_buffers, false, "Creates a jump list of lines from all buffers that appear to define or declare functions.")
COMMAND(list_all_functions_all_buffers_lister, true, "Creates a lister of locations that look like function definitions and declarations all buffers.")
COMMAND(list_all_functions_current_buffer, false, "Creates a jump list of lines of the current buffer that appear to define or declare functions.")
COMMAND(list_all_functions_current_buffer_lister, true, "Creates a lister of locations that look like function definitions and declarations in the buffer.")
COMMAND(list_all_locations, false, "Queries the user for a string and lists all exact case-sensitive matches found in all open buffers.")
COMMAND(list_all_locations_case_insensitive, false, "Queries the user for a string and lists all exact case-insensitive matches found in all open buffers.")
COMMAND(list_all_locations_of_identifier, false, "Reads a token or word under the cursor and lists all exact case-sensitive mathces in all open buffers.")
COMMAND(list_all_locations_of_identifier_case_insensitive, false, "Reads a token or word under the cursor and lists all exact case-insensitive mathces in all open buffers.")
COMMAND(list_all_locations_of_selection, false, "Reads the string in the selected range and lists all exact case-sensitive mathces in all open buffers.")
COMMAND(list_all_locations_of_selection_case_insensitive, false, "Reads the string in the selected range and lists all exact case-insensitive mathces in all open buffers.")
COMMAND(list_all_locations_of_type_definition, false, "Queries user for string, lists all locations of strings that appear to define a type whose name matches the input string.")
COMMAND(list_all_locations_of_type_definition_of_identifier, false, "Reads a token or word under the cursor and lists all locations of strings that appear to define a type whose name matches it.")
COMMAND(list_all_substring_locations, false, "Queries the user for a string and lists all case-sensitive substring matches found in all open buffers.")
COMMAND(list_all_substring_locations_case_insensitive, false, "Queries the user for a string and lists all case-insensitive substring matches found in all open buffers.")
COMMAND(load_project, false, "Looks for a project.5ed file in the current directory and tries to load it.  Looks in parent directories until a project file is found or there are no more parents.")
COMMAND(load_theme_current_buffer, false, "Parse the current buffer as a theme file and add the theme to the theme list. If the buffer has a .5ed postfix in it's name, it is removed when the name is saved.")
COMMAND(load_themes_default_folder, false, "Loads all the theme files in the default theme folder.")
COMMAND(load_themes_hot_directory, false, "Loads all the theme files in the current hot directory.")
COMMAND(make_directory_query, false, "Queries the user for a name and creates a new directory with the given name.")
COMMAND(miblo_decrement_basic, false, "Decrement an integer under the cursor by one.")
COMMAND(miblo_decrement_time_stamp, false, "Decrement a time stamp under the cursor by one second. (format [m]m:ss or h:mm:ss")
COMMAND(miblo_decrement_time_stamp_minute, false, "Decrement a time stamp under the cursor by one minute. (format [m]m:ss or h:mm:ss")
COMMAND(miblo_increment_basic, false, "Increment an integer under the cursor by one.")
COMMAND(miblo_increment_time_stamp, false, "Increment a time stamp under the cursor by one second. (format [m]m:ss or h:mm:ss")
COMMAND(miblo_increment_time_stamp_minute, false, "Increment a time stamp under the cursor by one minute. (format [m]m:ss or h:mm:ss")
COMMAND(mouse_wheel_change_face_size, false, "Reads the state of the mouse wheel and uses it to either increase or decrease the face size.")
COMMAND(mouse_wheel_scroll, false, "Reads the scroll wheel value from the mouse state and scrolls accordingly.")
COMMAND(move_down, false, "Moves the cursor down one line.")
COMMAND(move_down_10, false, "Moves the cursor down ten lines.")
COMMAND(move_down_textual, false, "Moves down to the next line of actual text, regardless of line wrapping.")
COMMAND(move_down_to_blank_line, false, "Seeks the cursor down to the next blank line.")
COMMAND(move_down_to_blank_line_end, false, "Seeks the cursor down to the next blank line and places it at the end of the line.")
COMMAND(move_down_to_blank_line_skip_whitespace, false, "Seeks the cursor down to the next blank line and places it at the end of the line.")
COMMAND(move_left, false, "Moves the cursor one character to the left.")
COMMAND(move_left_alpha_numeric_boundary, false, "Seek left for boundary between alphanumeric characters and non-alphanumeric characters.")
COMMAND(move_left_alpha_numeric_or_camel_boundary, false, "Seek left for boundary between alphanumeric characters or camel case word and non-alphanumeric characters.")
COMMAND(move_left_token_boundary, false, "Seek left for the next beginning of a token.")
COMMAND(move_left_whitespace_boundary, false, "Seek left for the next boundary between whitespace and non-whitespace.")
COMMAND(move_left_whitespace_or_token_boundary, false, "Seek left for the next end of a token or boundary between whitespace and non-whitespace.")
COMMAND(move_line_down, false, "Swaps the line under the cursor with the line below it, and moves the cursor down with it.")
COMMAND(move_line_up, false, "Swaps the line under the cursor with the line above it, and moves the cursor up with it.")
COMMAND(move_right, false, "Moves the cursor one character to the right.")
COMMAND(move_right_alpha_numeric_boundary, false, "Seek right for boundary between alphanumeric characters and non-alphanumeric characters.")
COMMAND(move_right_alpha_numeric_or_camel_boundary, false, "Seek right for boundary between alphanumeric characters or camel case word and non-alphanumeric characters.")
COMMAND(move_right_token_boundary, false, "Seek right for the next end of a token.")
COMMAND(move_right_whitespace_boundary, false, "Seek right for the next boundary between whitespace and non-whitespace.")
COMMAND(move_right_whitespace_or_token_boundary, false, "Seek right for the next end of a token or boundary between whitespace and non-whitespace.")
COMMAND(move_up, false, "Moves the cursor up one line.")
COMMAND(move_up_10, false, "Moves the cursor up ten lines.")
COMMAND(move_up_to_blank_line, false, "Seeks the cursor up to the next blank line.")
COMMAND(move_up_to_blank_line_end, false, "Seeks the cursor up to the next blank line and places it at the end of the line.")
COMMAND(move_up_to_blank_line_skip_whitespace, false, "Seeks the cursor up to the next blank line and places it at the end of the line.")
COMMAND(multi_paste, false, "Paste multiple entries from the clipboard at once")
COMMAND(multi_paste_interactive, false, "Paste multiple lines from the clipboard history, controlled with arrow keys")
COMMAND(multi_paste_interactive_quick, false, "Paste multiple lines from the clipboard history, controlled by inputing the number of lines to paste")
COMMAND(music_start, false, "Starts the music.")
COMMAND(music_stop, false, "Stops the music.")
COMMAND(open_all_code, false, "Open all code in the current directory. File types are determined by extensions. An extension is considered code based on the extensions specified in 5ed.config.")
COMMAND(open_all_code_recursive, false, "Works as open_all_code but also runs in all subdirectories.")
COMMAND(open_file_in_quotes, false, "Reads a filename from surrounding '\"' characters and attempts to open the corresponding file.")
COMMAND(open_in_other, false, "Interactively opens a file in the other panel.")
COMMAND(open_long_braces, false, "At the cursor, insert a '{' and '}' separated by a blank line.")
COMMAND(open_long_braces_break, false, "At the cursor, insert a '{' and '}break;' separated by a blank line.")
COMMAND(open_long_braces_semicolon, false, "At the cursor, insert a '{' and '};' separated by a blank line.")
COMMAND(open_matching_file_cpp, false, "If the current file is a *.cpp or *.h, attempts to open the corresponding *.h or *.cpp file in the other view.")
COMMAND(open_panel_hsplit, false, "Create a new panel by horizontally splitting the active panel.")
COMMAND(open_panel_vsplit, false, "Create a new panel by vertically splitting the active panel.")
COMMAND(page_down, false, "Scrolls the view down one view height and moves the cursor down one view height.")
COMMAND(page_up, false, "Scrolls the view up one view height and moves the cursor up one view height.")
COMMAND(paste, false, "At the cursor, insert the text at the top of the clipboard.")
COMMAND(paste_and_indent, false, "Paste from the top of clipboard and run auto-indent on the newly pasted text.")
COMMAND(paste_next, false, "If the previous command was paste or paste_next, replaces the paste range with the next text down on the clipboard, otherwise operates as the paste command.")
COMMAND(paste_next_and_indent, false, "Paste the next item on the clipboard and run auto-indent on the newly pasted text.")
COMMAND(place_in_scope, false, "Wraps the code contained in the range between cursor and mark with a new curly brace scope.")
COMMAND(play_with_a_counter, false, "Example of query bar")
COMMAND(profile_clear, false, "Clear all profiling information from 5ed's self profiler.")
COMMAND(profile_disable, false, "Prevent 5ed's self profiler from gathering new profiling information.")
COMMAND(profile_enable, false, "Allow 5ed's self profiler to gather new profiling information.")
COMMAND(profile_inspect, true, "Inspect all currently collected profiling information in 5ed's self profiler.")
COMMAND(project_command_F1, false, "Run the command with index 1")
COMMAND(project_command_F10, false, "Run the command with index 10")
COMMAND(project_command_F11, false, "Run the command with index 11")
COMMAND(project_command_F12, false, "Run the command with index 12")
COMMAND(project_command_F13, false, "Run the command with index 13")
COMMAND(project_command_F14, false, "Run the command with index 14")
COMMAND(project_command_F15, false, "Run the command with index 15")
COMMAND(project_command_F16, false, "Run the command with index 16")
COMMAND(project_command_F2, false, "Run the command with index 2")
COMMAND(project_command_F3, false, "Run the command with index 3")
COMMAND(project_command_F4, false, "Run the command with index 4")
COMMAND(project_command_F5, false, "Run the command with index 5")
COMMAND(project_command_F6, false, "Run the command with index 6")
COMMAND(project_command_F7, false, "Run the command with index 7")
COMMAND(project_command_F8, false, "Run the command with index 8")
COMMAND(project_command_F9, false, "Run the command with index 9")
COMMAND(project_command_lister, false, "Open a lister of all commands in the currently loaded project.")
COMMAND(project_fkey_command, false, "Run an 'fkey command' configured in a project.5ed file.  Determines the index of the 'fkey command' by which function key or numeric key was pressed to trigger the command.")
COMMAND(project_go_to_root_directory, false, "Changes 5ed's hot directory to the root directory of the currently loaded project. With no loaded project nothing hapepns.")
COMMAND(project_reprint, false, "Prints the current project to the file it was loaded from; prints in the most recent project file version")
COMMAND(query_replace, false, "Queries the user for two strings, and incrementally replaces every occurence of the first string with the second string.")
COMMAND(query_replace_identifier, false, "Queries the user for a string, and incrementally replace every occurence of the word or token found at the cursor with the specified string.")
COMMAND(query_replace_selection, false, "Queries the user for a string, and incrementally replace every occurence of the string found in the selected range with the specified string.")
COMMAND(quick_swap_buffer, false, "Change to the most recently used buffer in this view - or to the top of the buffer stack if the most recent doesn't exist anymore")
COMMAND(redo, false, "Advances forwards through the undo history of the current buffer.")
COMMAND(redo_all_buffers, false, "Advances forward through the undo history in the buffer containing the most recent regular edit.")
COMMAND(rename_file_query, false, "Queries the user for a new name and renames the file of the current buffer, altering the buffer's name too.")
COMMAND(reopen, false, "Reopen the current buffer from the hard drive.")
COMMAND(replace_in_all_buffers, false, "Queries the user for a needle and string. Replaces all occurences of needle with string in all editable buffers.")
COMMAND(replace_in_buffer, false, "Queries the user for a needle and string. Replaces all occurences of needle with string in the active buffer.")
COMMAND(replace_in_range, false, "Queries the user for a needle and string. Replaces all occurences of needle with string in the range between cursor and the mark in the active buffer.")
COMMAND(reverse_search, false, "Begins an incremental search up through the current buffer for a user specified string.")
COMMAND(reverse_search_identifier, false, "Begins an incremental search up through the current buffer for the word or token under the cursor.")
COMMAND(save, false, "Saves the current buffer.")
COMMAND(save_all_dirty_buffers, false, "Saves all buffers marked dirty (showing the '*' indicator).")
COMMAND(save_to_query, false, "Queries the user for a file name and saves the contents of the current buffer, altering the buffer's name too.")
COMMAND(search, false, "Begins an incremental search down through the current buffer for a user specified string.")
COMMAND(search_identifier, false, "Begins an incremental search down through the current buffer for the word or token under the cursor.")
COMMAND(seek_beginning_of_line, false, "Seeks the cursor to the beginning of the visual line.")
COMMAND(seek_beginning_of_textual_line, false, "Seeks the cursor to the beginning of the line across all text.")
COMMAND(seek_end_of_line, false, "Seeks the cursor to the end of the visual line.")
COMMAND(seek_end_of_textual_line, false, "Seeks the cursor to the end of the line across all text.")
COMMAND(select_all, false, "Puts the cursor at the top of the file, and the mark at the bottom of the file.")
COMMAND(select_next_scope_absolute, false, "Finds the first scope started by '{' after the cursor and puts the cursor and mark on the '{' and '}'.")
COMMAND(select_next_scope_after_current, false, "If a scope is selected, find first scope that starts after the selected scope. Otherwise find the first scope that starts after the cursor.")
COMMAND(select_prev_scope_absolute, false, "Finds the first scope started by '{' before the cursor and puts the cursor and mark on the '{' and '}'.")
COMMAND(select_prev_top_most_scope, false, "Finds the first scope that starts before the cursor, then finds the top most scope that contains that scope.")
COMMAND(select_surrounding_scope, false, "Finds the scope enclosed by '{' '}' surrounding the cursor and puts the cursor and mark on the '{' and '}'.")
COMMAND(select_surrounding_scope_maximal, false, "Selects the top-most scope that surrounds the cursor.")
COMMAND(set_eol_mode_from_contents, false, "Sets the buffer's line ending mode to match the contents of the buffer.")
COMMAND(set_eol_mode_to_binary, false, "Puts the buffer in bin line ending mode.")
COMMAND(set_eol_mode_to_crlf, false, "Puts the buffer in crlf line ending mode.")
COMMAND(set_eol_mode_to_lf, false, "Puts the buffer in lf line ending mode.")
COMMAND(set_face_size, false, "Set face size of the face used by the current buffer.")
COMMAND(set_face_size_this_buffer, false, "Set face size of the face used by the current buffer; if any other buffers are using the same face a new face is created so that only this buffer is effected")
COMMAND(set_mark, false, "Sets the mark to the current position of the cursor.")
COMMAND(set_mode_to_notepad_like, false, "Sets the edit mode to Notepad like.")
COMMAND(set_mode_to_original, false, "Sets the edit mode to 5ed original.")
COMMAND(setup_build_sh, false, "Queries the user for several configuration options and initializes a new build shell script.")
COMMAND(setup_new_project, false, "Queries the user for several configuration options and initializes a new 5ed project with a build shell script.")
COMMAND(show_filebar, false, "Sets the current view to show it's filebar.")
COMMAND(show_scrollbar, false, "Sets the current view to show it's scrollbar.")
COMMAND(show_the_log_graph, true, "Parses *log* and displays the 'log graph' UI")
COMMAND(snipe_backward_whitespace_or_token_boundary, false, "Delete a single, whole token on or to the left of the cursor and post it to the clipboard.")
COMMAND(snipe_forward_whitespace_or_token_boundary, false, "Delete a single, whole token on or to the right of the cursor and post it to the clipboard.")
COMMAND(snippet_lister, true, "Opens a snippet lister for inserting whole pre-written snippets of text.")
COMMAND(string_repeat, false, "Example of query_user_string and query_user_number")
COMMAND(suppress_mouse, false, "Hides the mouse and causes all mosue input (clicks, position, wheel) to be ignored.")
COMMAND(swap_panels, false, "Swaps the active panel with it's sibling.")
COMMAND(theme_lister, true, "Opens an interactive list of all registered themes.")
COMMAND(to_lowercase, false, "Converts all ascii text in the range between the cursor and the mark to lowercase.")
COMMAND(to_uppercase, false, "Converts all ascii text in the range between the cursor and the mark to uppercase.")
COMMAND(toggle_filebar, false, "Toggles the visibility status of the current view's filebar.")
COMMAND(toggle_fps_meter, false, "Toggles the visibility of the FPS performance meter")
COMMAND(toggle_fullscreen, false, "Toggle fullscreen mode on or off.  The change(s) do not take effect until the next frame.")
COMMAND(toggle_highlight_enclosing_scopes, false, "In code files scopes surrounding the cursor are highlighted with distinguishing colors.")
COMMAND(toggle_highlight_line_at_cursor, false, "Toggles the line highlight at the cursor.")
COMMAND(toggle_line_numbers, false, "Toggles the left margin line numbers.")
COMMAND(toggle_line_wrap, false, "Toggles the line wrap setting on this buffer.")
COMMAND(toggle_mouse, false, "Toggles the mouse suppression mode, see suppress_mouse and allow_mouse.")
COMMAND(toggle_paren_matching_helper, false, "In code files matching parentheses pairs are colored with distinguishing colors.")
COMMAND(toggle_show_whitespace, false, "Toggles the current buffer's whitespace visibility status.")
COMMAND(toggle_virtual_whitespace, false, "Toggles virtual whitespace for all files.")
COMMAND(tutorial_maximize, false, "Expand the tutorial window")
COMMAND(tutorial_minimize, false, "Shrink the tutorial window")
COMMAND(uncomment_line, false, "If present, delete '//' at the beginning of the line after leading whitespace.")
COMMAND(undo, false, "Advances backwards through the undo history of the current buffer.")
COMMAND(undo_all_buffers, false, "Advances backward through the undo history in the buffer containing the most recent regular edit.")
COMMAND(view_buffer_other_panel, false, "Set the other non-active panel to view the buffer that the active panel views, and switch to that panel.")
COMMAND(view_jump_list_with_lister, false, "When executed on a buffer with jumps, creates a persistent lister for all the jumps")
COMMAND(word_complete, false, "Iteratively tries completing the word to the left of the cursor with other words in open buffers that have the same prefix string.")
COMMAND(word_complete_drop_down, false, "Word complete with drop down menu.")
COMMAND(write_block, false, "At the cursor, insert a block comment.")
COMMAND(write_hack, false, "At the cursor, insert a '// HACK' comment, includes user name if it was specified in config.5ed.")
COMMAND(write_note, false, "At the cursor, insert a '// NOTE' comment, includes user name if it was specified in config.5ed.")
COMMAND(write_space, false, "Inserts a space.")
COMMAND(write_text_and_auto_indent, false, "Inserts text and auto-indents the line on which the cursor sits if any of the text contains 'layout punctuation' such as ;:{}()[]# and new lines.")
COMMAND(write_text_input, false, "Inserts whatever text was used to trigger this command.")
COMMAND(write_todo, false, "At the cursor, insert a '// TODO' comment, includes user name if it was specified in config.5ed.")
COMMAND(write_underscore, false, "Inserts an underscore.")
COMMAND(write_zero_struct, false, "At the cursor, insert a ' = {};'.")
